### PR TITLE
MLBAM and Fangraphs player references

### LINKED ISSUE #67: Will Smiths are merged
Not sure if this is a web-app import problem only or if the sqlite import is also broken.

Presumably should be fixed in the database and the import process(es) should be updated, though the web-app import is going to be hard to get right.

### PR DESCRIPTION
**Pull request by eschenfeldt**
Aggregate reference data and use it to disambiguate players during import, which fixes #67. Also sets Fangraphs URLs for future use.

### CODE REVIEW

File: BaseballApi/Api/Models/BaseballContext.cs [hunk 1]
```diff
@@ -12,6 +13,20 @@ public BaseballContext(DbContextOptions<BaseballContext> options) : base(options
     public DbSet<Player> Players { get; set; }
 
     public DbSet<BoxScore> BoxScores { get; set; }
+    public IQueryable<BoxScorePlayer> BoxScorePlayers => this.BoxScores
```
Comment (eschenfeldt) [inline BaseballApi/Api/Models/BaseballContext.cs]: Remove

File: BaseballApi/Api/Models/BoxScorePlayer.cs [hunk 2]
```diff
@@ -0,0 +1,14 @@
+using System;
+
+namespace BaseballApi.Models;
+
+/**
+ * Represents a player in a box score, regardless of specific role. Only used as a computed property.
+ */
+public class BoxScorePlayer
```
Comment (eschenfeldt) [inline BaseballApi/Api/Models/BoxScorePlayer.cs]: Remove

File: BaseballApi/Api/Integrations/ReferenceManager.cs [hunk 3]
```diff
@@ -0,0 +1,276 @@
...
+        {
+            PlayersUpdated = playerUpdateCount,
+            ReferencePlayersUpdated = referencePlayerUpdateCount
+        };
+    }
+
+    private Player? MatchPlayerByMLBAMPlayer(ReferencePlayer referencePlayer, MLBAMPlayer mlbamPlayer)
+    {
+        // First match by name and date of birth
+        var player = Context.Players.FirstOrDefault(p => EF.Functions.Unaccent(p.Name) == EF.Functions.Unaccent(mlbamPlayer.FullName) && p.DateOfBirth == referencePlayer.DateOfBirth);
```
[the remark this answers is not in the document]
Comment (eschenfeldt) [reply BaseballApi/Api/Integrations/ReferenceManager.cs]: Or possibly name_normalized isn't really being used now and should be removed?
